wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.21
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.5
    start_time: 1660616695
    t:
      1:
      - 2
      - 3
      - 5
      - 53
      - 55
      4: 3.8.5
      5: 0.12.21
      8:
      - 3
      - 5
